databases:
  - name: westminster-db
    plan: free
    databaseName: westminster
    user: westminster

services:
  - type: web
    name: westminster
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: westminster-db
          property: connectionURI
      - key: ALLOWED_HOSTS
        value: .onrender.com,.studyreformed.com
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
